name: Flutter Build (Semantic Version + Auto Build Numbers)

on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master]

jobs:
 version-control:
  name: Version Control
  runs-on: ubuntu-latest
  outputs:
    app_version: ${{ steps.version.outputs.version }}
    build_number: ${{ steps.version.outputs.build_number }}
  steps:
    - uses: actions/checkout@v4
    - name: Extract version
      id: version
      run: |
        FULL_VERSION=$(grep 'version:' pubspec.yaml | awk '{print $2}' | tr -d '"')
        echo "version=${FULL_VERSION%+*}" >> $GITHUB_OUTPUT
        echo "build_number=${FULL_VERSION#*+}" >> $GITHUB_OUTPUT

 android:
    name: Android Build
    needs: version-control
    runs-on: ubuntu-latest
    env:
      APP_VERSION: ${{ needs.version-control.outputs.app_version }}
      BUILD_NUMBER: ${{ needs.version-control.outputs.build_number }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          cache: true

      - run: flutter pub get
      - run: flutter build apk --release --build-name=$APP_VERSION --build-number=$BUILD_NUMBER
      - run: flutter build appbundle --release --build-name=$APP_VERSION --build-number=$BUILD_NUMBER

      - uses: actions/upload-artifact@v4
        with:
          name: android-build-${{ env.BUILD_NUMBER }}
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab

 ios:
    name: iOS Build
    needs: version-control
    runs-on: macos-latest
    env:
      APP_VERSION: ${{ needs.version-control.outputs.app_version }}
      BUILD_NUMBER: ${{ needs.version-control.outputs.build_number }}

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          cache: true

      - run: flutter pub get
      - run: flutter build ios --release --no-codesign --build-name=$APP_VERSION --build-number=$BUILD_NUMBER

      - uses: actions/upload-artifact@v4
        with:
          name: ios-build-${{ env.BUILD_NUMBER }}
          path: build/ios/iphoneos/Runner.app

 release:
  name: Create Release
  if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
  needs: [version-control, android, ios]
  runs-on: ubuntu-latest
  permissions:
    contents: write

  steps:
    - name: Download Android Artifact
      uses: actions/download-artifact@v4
      with:
        name: android-build-${{ needs.version-control.outputs.build_number }}
        path: artifacts/android/

    - name: Download iOS Artifact
      uses: actions/download-artifact@v4
      with:
        name: ios-build-${{ needs.version-control.outputs.build_number }}
        path: artifacts/ios/

    - name: Verify Files
      run: |
        echo "Checking downloaded artifacts:"
        ls -R artifacts/
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ needs.version-control.outputs.app_version }}+${{ needs.version-control.outputs.build_number }}
        files: |
          artifacts/android/flutter-apk/app-release.apk
          artifacts/android/bundle/release/app-release.aab
          artifacts/ios/Runner