name: Flutter CI/CD Pipeline

on:
  push:
    branches: ['**']  # All branches
    tags: ['*']       # All tags
  pull_request:
    branches: [main, master]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
      
      - name: Check for test dependencies
        id: check_tests
        run: |
          if grep -q "flutter_test:" pubspec.yaml; then
            echo "has_tests=true" >> $GITHUB_OUTPUT
          else
            echo "has_tests=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Run Tests (if available)
        if: steps.check_tests.outputs.has_tests == 'true'
        run: |
          flutter pub get
          flutter test
      
      - name: Skip Tests (no dependencies)
        if: steps.check_tests.outputs.has_tests == 'false'
        run: echo "Skipping tests - no flutter_test dependency found"

  # Runs on main/master pushes AND any tag (including experimental)
  build:
    name: Build Artifacts
    needs: test
    if: |
      github.event_name == 'push' && (
        github.ref == 'refs/heads/main' ||
        github.ref == 'refs/heads/master' ||
        startsWith(github.ref, 'refs/tags/'))
    strategy:
      matrix:
        platform: [android]  # Removed iOS
    runs-on: ubuntu-latest   # No need for macOS since iOS is removed
    
    steps:
      - uses: actions/checkout@v4
      - name: Extract version info
        id: version
        shell: bash
        run: |
            # Debug: Show current ref
            echo "GITHUB_REF: $GITHUB_REF"
            
            # For tags, use tag name as version
            if [[ "$GITHUB_REF" == refs/tags/* ]]; then
                TAG_NAME=${GITHUB_REF#refs/tags/}
                echo "VERSION=$TAG_NAME" >> $GITHUB_ENV
                echo "BUILD_NUMBER=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
                echo "Extracted from tag: VERSION=$TAG_NAME, BUILD_NUMBER=$(date +%Y%m%d%H%M)"
            else
                # For branches, use pubspec version
                FULL_VERSION=$(grep 'version:' pubspec.yaml | awk '{print $2}' | tr -d '"')
                echo "VERSION=${FULL_VERSION%+*}" >> $GITHUB_ENV
                echo "BUILD_NUMBER=${FULL_VERSION#*+}" >> $GITHUB_ENV
                echo "Extracted from pubspec: VERSION=${FULL_VERSION%+*}, BUILD_NUMBER=${FULL_VERSION#*+}"
            fi
            
            # Debug: Show extracted values
            echo "Extracted VERSION: $VERSION"
            echo "Extracted BUILD_NUMBER: $BUILD_NUMBER"

      - name: Setup Java (Android only)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          cache: true

      - name: Build Android
        run: |
          flutter build apk --release \
            --build-name=$VERSION --build-number=$BUILD_NUMBER
          flutter build appbundle --release \
            --build-name=$VERSION --build-number=$BUILD_NUMBER
          mkdir -p artifacts/android
          cp build/app/outputs/flutter-apk/app-release.apk artifacts/android/app-$VERSION+$BUILD_NUMBER.apk
          cp build/app/outputs/bundle/release/app-release.aab artifacts/android/app-$VERSION+$BUILD_NUMBER.aab

      - name: List Artifacts Before Upload (Debug)
        run: |
          echo "Generated artifacts:"
          ls -R artifacts/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-artifacts-${{ env.BUILD_NUMBER }}
          path: artifacts/android/*
          retention-days: 7

  # Only creates releases for main/master (not experimental tags)
  release:
    name: Create Release
    needs: build
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: "*-artifacts-*"
          merge: true
      
      - name: List Downloaded Artifacts (Debug)
        run: |
          echo "Downloaded artifacts:"
          ls -R

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}+${{ env.BUILD_NUMBER }}
          name: v${{ env.VERSION }}
          files: |
            *-artifacts-*/*.apk
            *-artifacts-*/*.aab 