name: Build iOS and Android Releases
on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.29.2'
          cache: true

      - name: Install dependencies
        run: |
          flutter pub get
          sudo gem install cocoapods

      - name: Extract version from pubspec
        id: version
        run: |
          FULL_VERSION=$(grep 'version:' pubspec.yaml | awk '{print $2}' | tr -d '"')
          echo "VERSION=${FULL_VERSION%+*}" >> $GITHUB_ENV
          echo "BUILD_NUMBER=${FULL_VERSION#*+}" >> $GITHUB_ENV
          echo "Using version: ${FULL_VERSION%+*} (build ${FULL_VERSION#*+})"

      - name: Build Android APK
        run: |
          flutter build apk --release --build-name=${{ env.VERSION }} --build-number=${{ env.BUILD_NUMBER }}

      - name: Build Android App Bundle
        run: |
          flutter build appbundle --release --build-name=${{ env.VERSION }} --build-number=${{ env.BUILD_NUMBER }}

      - name: Build iOS IPA
        run: |
          flutter build ipa --release --no-codesign --build-name=${{ env.VERSION }} --build-number=${{ env.BUILD_NUMBER }}

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts
          cp build/app/outputs/flutter-apk/app-release.apk artifacts/
          cp build/app/outputs/bundle/release/app-release.aab artifacts/
          cp build/ios/ipa/*.ipa artifacts/

      - name: Upload artifacts
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || || github.ref == 'refs/heads/dev')
        uses: actions/upload-artifact@v4
        with:
          name: app-build-${{ github.run_number }}
          path: artifacts/
          retention-days: 7

      - name: Create Release (main/master only)
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || || github.ref == 'refs/heads/dev')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}+${{ env.BUILD_NUMBER }}
          name: v${{ env.VERSION }} (Build ${{ env.BUILD_NUMBER }})
          files: |
            artifacts/app-release.apk
            artifacts/app-release.aab
            artifacts/*.ipa
          body: |
            ### Version ${{ env.VERSION }}+${{ env.BUILD_NUMBER }}
            Built from branch: ${{ github.ref_name }}
            Workflow run: ${{ github.run_number }}