name: Build iOS and Android Releases
on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      build_number: ${{ steps.version.outputs.build_number }}
    steps:
      - uses: actions/checkout@v4
      - name: Extract version
        id: version
        run: |
          FULL_VERSION=$(grep 'version:' pubspec.yaml | awk '{print $2}' | tr -d '"')
          echo "version=${FULL_VERSION%+*}" >> $GITHUB_OUTPUT
          echo "build_number=${FULL_VERSION#*+}" >> $GITHUB_OUTPUT

  android:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.19.0'
          cache: true
      - run: flutter pub get
      - run: |
          flutter build apk --release \
            --build-name=${{ needs.setup.outputs.version }} \
            --build-number=${{ needs.setup.outputs.build_number }}
          flutter build appbundle --release \
            --build-name=${{ needs.setup.outputs.version }} \
            --build-number=${{ needs.setup.outputs.build_number }}
      - uses: actions/upload-artifact@v4
        with:
          name: android-artifacts
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
          retention-days: 7
          

  ios:
    needs: setup
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.19.0'
          cache: true
      - run: |
          flutter pub get
      - run: |
          flutter build ios --release --no-codesign \
            --build-name=${{ needs.setup.outputs.version }} \
            --build-number=${{ needs.setup.outputs.build_number }}
      - uses: actions/upload-artifact@v4
        with:
          name: ios-artifacts
          path: build/ios/iphoneos/Runner.app
          retention-days: 7

  release:
    needs: [android, ios]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: android-artifacts
          path: artifacts/android
      - uses: actions/download-artifact@v4
        with:
          name: ios-artifacts
          path: artifacts/ios
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.setup.outputs.version }}+${{ needs.setup.outputs.build_number }}
          name: v${{ needs.setup.outputs.version }} (Build ${{ needs.setup.outputs.build_number }})
          files: |
            artifacts/android/app-release.apk
            artifacts/android/app-release.aab
            artifacts/ios/Runner.app
          body: |
            ### Version ${{ needs.setup.outputs.version }}+${{ needs.setup.outputs.build_number }}
            Built from branch: ${{ github.ref_name }}
            Workflow run: ${{ github.run_number }}